apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: smarthealthacr.azurecr.io/backend:latest   # Replace with your ACR name if different
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
